# Generated by Django 4.2.3 on 2023-09-18 03:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('about_me', models.TextField(blank=True, default='')),
                ('interests', models.CharField(blank=True, choices=[('Architecture', 'Architecture'), ('Art', 'Art'), ('Engineering', 'Engineering'), ('Education', 'Education'), ('Management', 'Management'), ('Business', 'Business'), ('Healthcare', 'Healthcare'), ('Software / Technology', 'Software / Technology'), ('Physical / Fitness', 'Physical / Fitness')], max_length=64, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
