# Generated by Django 4.2.3 on 2023-09-18 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about_me',
            field=models.TextField(blank=True, default='No about me yet.'),
        ),
        migrations.AddField(
            model_name='user',
            name='interests',
            field=models.CharField(blank=True, choices=[('Architecture', 'Architecture'), ('Art', 'Art'), ('Engineering', 'Engineering'), ('Education', 'Education'), ('Management', 'Management'), ('Business', 'Business'), ('Healthcare', 'Healthcare'), ('Software / Technology', 'Software / Technology'), ('Physical / Fitness', 'Physical / Fitness')], max_length=64, null=True),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
