# Generated by Django 4.2.3 on 2023-09-28 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0004_remove_user_interests_user_interests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobposting',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='jobposting',
            old_name='desc',
            new_name='description',
        ),
        migrations.AddField(
            model_name='user',
            name='bookmarks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='jobseeker.jobposting'),
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicants', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('job_posting', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='jobseeker.jobposting')),
            ],
        ),
    ]
