# Generated by Django 4.2.3 on 2023-09-28 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0005_rename_user_jobposting_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bookmarks',
        ),
        migrations.AddField(
            model_name='user',
            name='bookmarks',
            field=models.ManyToManyField(blank=True, to='jobseeker.jobposting'),
        ),
    ]
