# Generated by Django 4.2.3 on 2023-09-28 06:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0007_jobposting_type_of_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='applicants',
            field=models.ManyToManyField(blank=True, related_name='applicants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='author',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='type_of_job',
            field=models.ManyToManyField(to='jobseeker.job', verbose_name='interests'),
        ),
        migrations.DeleteModel(
            name='JobApplication',
        ),
    ]
