# Generated by Django 4.2.3 on 2023-09-30 09:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0008_jobposting_applicants_alter_jobposting_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobposting',
            name='author',
        ),
        migrations.AddField(
            model_name='jobposting',
            name='creator',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL),
        ),
    ]
