# Generated by Django 4.2.3 on 2023-09-30 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0009_remove_jobposting_author_jobposting_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
